#!/usr/bin/env node
/**
 * Generates the SDK's API surface from the services' curated `agent-tools`
 * OpenAPI specs (the same specs the AI agents import as tool servers).
 *
 * The specs are committed under `specs/` so codegen is reproducible offline and
 * a spec change shows up as a reviewable diff. Refresh them with
 * `npm run codegen:fetch`, then re-run this.
 *
 * Emitted (all of `src/generated/` is overwritten — never hand-edit it):
 *   runtime.ts     — request helper shared by the generated classes
 *   <service>.ts   — one class per service, one method per operation
 *   operations.ts  — flat registry of every operation (drives the MCP server)
 *   index.ts       — barrel + GeneratedApi
 *
 * The specs carry typed inputs (path/query/body) but no response schemas, so
 * methods return `unknown` by default and take a `<T>` so callers can name the
 * shape they expect. Hand-written resources in `src/resources/` keep their real
 * response types and stay the recommended surface for the endpoints they cover.
 */
import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const ROOT = join(HERE, '..', '..')          // repo root (api-sdk/)
const SPEC_DIR = join(ROOT, 'specs')
const OUT_DIR = join(ROOT, 'ts', 'src', 'generated')

/**
 * Spec file -> generated class + the base URL it is served from.
 *
 * `base` is an expression evaluated in client.ts against the resolved
 * ServiceUrls. Each was verified against the live gateway; the spec's own
 * `servers[0]` is the service's internal cluster URL and is deliberately
 * ignored.
 */
const SERVICES = [
  { spec: 'data-board',  key: 'dataBoard',   cls: 'DataBoardApi',   base: 'urls.dataBoard' },
  { spec: 'channel',     key: 'channel',     cls: 'ChannelApi',     base: '`${urls.channelService}/v1`' },
  { spec: 'platform',    key: 'platform',    cls: 'PlatformApi',    base: '`${urls.platform}/v1`' },
  { spec: 'marketplace', key: 'marketplace', cls: 'MarketplaceApi', base: '`${urls.gateway}/v3/marketplaces`' },
  { spec: 'workflow',    key: 'workflow',    cls: 'WorkflowApi',    base: 'urls.workflowEngine' },
]

const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete']
const BANNER = `// AUTO-GENERATED by scripts/generate-api.mjs — DO NOT EDIT.\n// Regenerate with \`npm run codegen\`.\n`

// ── schema -> TypeScript ────────────────────────────────────────────────────

const IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/
const key = (k) => (IDENT.test(k) ? k : JSON.stringify(k))
/** Escape a literal segment for embedding in a generated template literal. */
const esc = (s) => s.replace(/[\\`$]/g, '\\$&')

function tsType(schema, depth = 0) {
  if (!schema || typeof schema !== 'object') return 'unknown'
  if (Array.isArray(schema.enum) && schema.enum.every((e) => typeof e === 'string')) {
    return schema.enum.map((e) => JSON.stringify(e)).join(' | ')
  }
  switch (schema.type) {
    case 'string':
      return 'string'
    case 'number':
    case 'integer':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'array': {
      const item = tsType(schema.items, depth + 1)
      return /[|&\s]/.test(item) ? `(${item})[]` : `${item}[]`
    }
    case 'object': {
      if (!schema.properties || depth > 6) return 'Record<string, unknown>'
      const required = new Set(schema.required ?? [])
      const props = Object.entries(schema.properties).map(
        ([k, v]) => `${key(k)}${required.has(k) ? '' : '?'}: ${tsType(v, depth + 1)}`,
      )
      return props.length ? `{ ${props.join('; ')} }` : 'Record<string, unknown>'
    }
    default:
      // No `type` at all — e.g. `items: {}`, which a few catalogs use for a list
      // whose element type they never spelled out. `unknown` is the honest read;
      // widening it to Record<string, unknown> would wrongly reject `string[]`.
      return schema.properties ? tsType({ ...schema, type: 'object' }, depth) : 'unknown'
  }
}

// ── operation model ─────────────────────────────────────────────────────────

function collect(service) {
  const spec = JSON.parse(readFileSync(join(SPEC_DIR, `${service.spec}.json`), 'utf8'))
  const ops = []

  for (const [path, item] of Object.entries(spec.paths ?? {})) {
    for (const method of HTTP_METHODS) {
      const op = item[method]
      if (!op) continue

      const params = op.parameters ?? []
      const pathParams = params.filter((p) => p.in === 'path')
      const queryParams = params.filter((p) => p.in === 'query')
      const bodySchema = op.requestBody?.content?.['application/json']?.schema

      // A path token with no matching `parameters` entry would silently generate
      // a broken URL, so treat it as a required string rather than dropping it.
      const declared = new Set(pathParams.map((p) => p.name))
      for (const m of path.matchAll(/\{([^}]+)\}/g)) {
        if (!declared.has(m[1])) {
          pathParams.push({ name: m[1], in: 'path', required: true, schema: { type: 'string' } })
        }
      }

      // The success response, when the service bothered to describe one. Most
      // catalogs still emit a bare `200: OK`; those methods stay `unknown`.
      const success = Object.entries(op.responses ?? {})
        .filter(([code]) => /^2\d\d$/.test(code))
        .sort(([a], [b]) => Number(a) - Number(b))[0]
      const responseSchema = success?.[1]?.content?.['application/json']?.schema

      ops.push({
        id: op.operationId,
        service: service.key,
        method: method.toUpperCase(),
        path,
        tag: op.tags?.[0] ?? 'default',
        summary: op.summary ?? '',
        write: op['x-write'] === true,
        destructive: op['x-destructive'] === true,
        pathParams,
        queryParams,
        bodySchema,
        bodyRequired: op.requestBody?.required === true,
        responseSchema,
      })
    }
  }

  ops.sort((a, b) => a.id.localeCompare(b.id))
  return ops
}

// ── emit: one class per service ─────────────────────────────────────────────

function emitMethod(op) {
  const fields = []
  for (const p of op.pathParams) {
    fields.push({ name: p.name, optional: false, type: tsType(p.schema), doc: p.description })
  }
  for (const p of op.queryParams) {
    fields.push({ name: p.name, optional: !p.required, type: tsType(p.schema), doc: p.description })
  }
  if (op.bodySchema) {
    fields.push({ name: 'body', optional: !op.bodyRequired, type: tsType(op.bodySchema) })
  }

  const allOptional = fields.every((f) => f.optional)
  const hasParams = fields.length > 0
  const arg = !hasParams
    ? ''
    : `params${allOptional ? '?' : ''}: { ${fields
        .map((f) => `${key(f.name)}${f.optional ? '?' : ''}: ${f.type}`)
        .join('; ')} }`
  const p = allOptional ? 'params?.' : 'params.'

  // `/boards/{id}` -> `` `/boards/${e(params.id)}` ``. Split first so the escaping
  // below only touches the literal segments — escaping the whole string would
  // turn the interpolations into literal `${…}` text and break every URL.
  const url = op.path
    .split(/(\{[^}]+\})/)
    .map((segment) => {
      const param = /^\{([^}]+)\}$/.exec(segment)
      return param ? `\${e(${p}${key(param[1])})}` : esc(segment)
    })
    .join('')

  const query = op.queryParams.length
    ? `{ ${op.queryParams.map((q) => `${key(q.name)}: ${p}${key(q.name)}`).join(', ')} }`
    : 'undefined'
  const body = op.bodySchema ? `${p}body` : 'undefined'

  const doc = [op.summary, op.destructive && '@destructive', op.write && !op.destructive && '@write']
    .filter(Boolean)
    .join(' — ')

  // Default to the response type when the service described one; otherwise
  // `unknown`, which forces the caller to say what they expect. Either way `<T>`
  // stays open, so a caller with a better type isn't fighting the generated one.
  const returns = op.responseSchema ? responseTypeName(op) : 'unknown'

  return [
    `  /** ${doc || op.id} */`,
    `  ${op.id}<T = ${returns}>(${arg}): Promise<T> {`,
    `    return this.req<T>(${JSON.stringify(op.method)}, \`${url}\`, ${query}, ${body})`,
    `  }`,
  ].join('\n')
}

const responseTypeName = (op) => `${op.id[0].toUpperCase()}${op.id.slice(1)}Response`

function emitService(service, ops) {
  const seen = new Set()
  const methods = []
  const types = []
  for (const op of ops) {
    if (seen.has(op.id)) {
      console.warn(`  ! duplicate operationId within ${service.spec}: ${op.id} (skipped)`)
      continue
    }
    seen.add(op.id)
    if (op.responseSchema) {
      types.push(`/** Response of \`${op.id}\` — from the route's own model. */\nexport type ${responseTypeName(op)} = ${tsType(op.responseSchema)}`)
    }
    methods.push(emitMethod(op))
  }

  const destructive = ops.filter((o) => o.destructive).length
  const typed = ops.filter((o) => o.responseSchema).length
  const untyped = methods.length - typed

  return `${BANNER}
import { GeneratedResource, e } from './runtime.js'

/**
 * ${service.spec} — ${methods.length} operations (${destructive} destructive).
 *
 * Generated from \`specs/${service.spec}.json\`.
 *
 * ${typed} operation(s) return a described shape; the other ${untyped} return \`unknown\`
 * because their catalog declares no response schema. Every method still takes a
 * type argument, so a caller can name a shape the spec doesn't know:
 * \`listBoards<{ data: Board[] }>()\`.
 */
export class ${service.cls} extends GeneratedResource {
${methods.join('\n\n')}
}
${types.length ? `\n${types.join('\n\n')}\n` : ''}`
}

// ── emit: operations registry ───────────────────────────────────────────────

function jsonSchemaFor(op) {
  const properties = {}
  const required = []
  for (const p of [...op.pathParams, ...op.queryParams]) {
    properties[p.name] = { ...p.schema, ...(p.description ? { description: p.description } : {}) }
    if (p.required || p.in === 'path') required.push(p.name)
  }
  if (op.bodySchema) {
    properties.body = op.bodySchema
    if (op.bodyRequired) required.push('body')
  }
  return { type: 'object', properties, ...(required.length ? { required } : {}) }
}

function emitOperations(all) {
  const entries = all.map((op) => {
    // operationIds are unique per service but collide across services
    // (listFolders, listFiles, …), so the registry key is service-qualified.
    const meta = {
      name: `${op.service}.${op.id}`,
      service: op.service,
      operationId: op.id,
      method: op.method,
      path: op.path,
      tag: op.tag,
      summary: op.summary,
      write: op.write,
      destructive: op.destructive,
      inputSchema: jsonSchemaFor(op),
    }
    return `  ${JSON.stringify(meta)},`
  })

  return `${BANNER}
/** One callable operation, as exported by a service's agent-tools spec. */
export interface OperationMeta {
  /** Service-qualified, globally unique — safe to use as an MCP tool name. */
  name: string
  service: 'dataBoard' | 'channel' | 'platform' | 'marketplace' | 'workflow'
  /** Method name on the matching generated class. Unique within its service only. */
  operationId: string
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
  path: string
  tag: string
  summary: string
  /** Mutates state. */
  write: boolean
  /** Destroys data. Gate these behind explicit opt-in. */
  destructive: boolean
  /** JSON Schema for the method's single \`params\` argument. */
  inputSchema: Record<string, unknown>
}

/** Every operation across the ${SERVICES.length} services (${all.length} total). */
export const OPERATIONS: readonly OperationMeta[] = [
${entries.join('\n')}
] as const

export const OPERATIONS_BY_NAME: ReadonlyMap<string, OperationMeta> = new Map(
  OPERATIONS.map((op) => [op.name, op]),
)
`
}

// ── emit: runtime + barrel ──────────────────────────────────────────────────

const RUNTIME = `${BANNER}
import type { HttpTransport } from '../http.js'

/** Path-segment encoder. Kept short — it appears in every generated URL. */
export const e = (v: string | number | boolean): string => encodeURIComponent(String(v))

/**
 * Base for the generated service classes.
 *
 * Auth, retries and error mapping live in HttpTransport, which throws AuthError
 * on 401/403 and ApiError on any other non-2xx, so this only has to build the
 * request and decode the body.
 */
export abstract class GeneratedResource {
  constructor(
    protected readonly http: HttpTransport,
    protected readonly base: string,
  ) {}

  protected async req<T>(
    method: string,
    path: string,
    query?: Record<string, unknown>,
    body?: unknown,
  ): Promise<T> {
    const url = new URL(this.base + path)

    for (const [k, v] of Object.entries(query ?? {})) {
      if (v === undefined || v === null) continue
      // Repeated key (\`?ids=a&ids=b\`) — several services reject comma-joined lists.
      if (Array.isArray(v)) for (const item of v) url.searchParams.append(k, String(item))
      else url.searchParams.set(k, String(v))
    }

    const init: RequestInit = { method }
    if (body !== undefined) {
      init.headers = { 'Content-Type': 'application/json' }
      init.body = JSON.stringify(body)
    }

    const res = await this.http.getFetch()(url, init)

    if (res.status === 204) return undefined as T
    const text = await res.text()
    if (!text) return undefined as T
    try {
      return JSON.parse(text) as T
    } catch {
      // A few endpoints answer with CSV or plain text.
      return text as unknown as T
    }
  }
}
`

function emitIndex(counts) {
  const imports = SERVICES.map((s) => `import { ${s.cls} } from './${s.spec}.js'`).join('\n')
  // `export *` (not just the class) so the generated response types are public.
  const reexports = SERVICES.map((s) => `export * from './${s.spec}.js'`).join('\n')
  const fields = SERVICES.map(
    (s) => `  /** ${s.spec} — ${counts[s.key]} operations. */\n  readonly ${s.key}: ${s.cls}`,
  ).join('\n')
  const init = SERVICES.map((s) => `    this.${s.key} = new ${s.cls}(http, bases.${s.key})`).join('\n')
  const baseFields = SERVICES.map((s) => `  ${s.key}: string`).join('\n')

  return `${BANNER}
import type { HttpTransport } from '../http.js'
${imports}

${reexports}
export { GeneratedResource, e } from './runtime.js'
export { OPERATIONS, OPERATIONS_BY_NAME } from './operations.js'
export type { OperationMeta } from './operations.js'

/** Base URL per service. Built in client.ts from the resolved ServiceUrls. */
export interface ApiBases {
${baseFields}
}

/**
 * Full generated API surface — every operation the services expose to agents.
 *
 * Reached as \`client.api\`. Prefer the hand-written resources (\`client.boards\`,
 * \`client.contacts\`, …) where they cover the endpoint: they have real response
 * types. This is the complete, always-in-sync surface underneath them.
 */
export class GeneratedApi {
${fields}

  constructor(http: HttpTransport, bases: ApiBases) {
${init}
  }
}
`
}

// ── run ─────────────────────────────────────────────────────────────────────

function main() {
  const specs = readdirSync(SPEC_DIR).filter((f) => f.endsWith('.json'))
  if (specs.length !== SERVICES.length) {
    console.warn(`! ${specs.length} spec files but ${SERVICES.length} services configured`)
  }

  mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(join(OUT_DIR, 'runtime.ts'), RUNTIME)

  const all = []
  const counts = {}

  for (const service of SERVICES) {
    const ops = collect(service)
    counts[service.key] = ops.length
    all.push(...ops)
    writeFileSync(join(OUT_DIR, `${service.spec}.ts`), emitService(service, ops))
    const w = ops.filter((o) => o.write && !o.destructive).length
    const d = ops.filter((o) => o.destructive).length
    console.log(
      `  ${service.spec.padEnd(12)} ${String(ops.length).padStart(3)} ops  (${ops.length - w - d} read, ${w} write, ${d} destructive)`,
    )
  }

  writeFileSync(join(OUT_DIR, 'operations.ts'), emitOperations(all))
  writeFileSync(join(OUT_DIR, 'index.ts'), emitIndex(counts))

  console.log(`  ${'TOTAL'.padEnd(12)} ${String(all.length).padStart(3)} operations -> src/generated/`)
}

main()
